Document: libesom
Title: Debian libesom Manual
Author: <insert document author here>
Abstract: This manual describes what libesom is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libesom/libesom.sgml.gz

Format: postscript
Files: /usr/share/doc/libesom/libesom.ps.gz

Format: text
Files: /usr/share/doc/libesom/libesom.text.gz

Format: HTML
Index: /usr/share/doc/libesom/html/index.html
Files: /usr/share/doc/libesom/html/*.html
